services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
    container_name: lifeplan-backend-local
    restart: unless-stopped

  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: lifeplan-frontend-local
    restart: unless-stopped 
 